### ISSUE TITLE
add module settings headline

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#23] opened 2024-04-09 15:50 UTC
@samuel.stroschein said in [INLMC-46](https://linear.app/opral/issue/INLMC-46/settings-component-save-float-doesnt-appear-after-first-edit-on#comment-824f945c):

> @nils.jacobsen i suggest to add a module settings header over module settings to signal "everything below here" is module related
>
> <img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/ecfab9eb-afed-4451-9e5f-278b26b3dda1/20fbed3a-ac7e-4a55-b044-436c61782da1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lY2ZhYjllYi1hZmVkLTQ0NTEtOWU1Zi0yNzhiMjZiM2RkYTEvMjBmYmVkM2EtYWM3ZS00YTU1LWIwNDQtNDM2YzYxNzgyZGExIiwiaWF0IjoxNzEyNjc3ODIwLCJleHAiOjMzMjgzMjM3ODIwfQ.HhKpjG5sQ0EW0GBQvJoPseO6no-dF4L8lgh1wNZMag4 " alt="CleanShot 2024-04-09 at 11.42.41@2x.png" width="1904" height="1090" />

**Comment by NilsJacobsen** [comment] 2024-04-10 07:19
This is a duplicate of [INLMC-13](https://linear.app/opral/issue/INLMC-13/the-floating-does-not-appear-if-i-change-something-a-second-time)

**Comment by NilsJacobsen** [comment] 2024-04-10 08:49
We can do this to make a separation.

Cons:

* A lot of headlines in one section makes it cluttered (we may resolve that with a divider line)
* Module settings might be a difficult word for non-techies

Pro: 

* Visual separation

Long term I think we want to have multiple pages for those settings with a sidebar.

**Comment by samuelstroschein** [comment] 2024-04-10 13:43
> Long term I think we want to have multiple pages for those settings with a sidebar.

Solid's trick is amazing [https://www.solidjs.com/guides/getting-started](https://www.solidjs.com/guides/getting-started) 

One large page but sidebar on the left is generated from h1 headers. Gives a "this are multiple sites" feeling without the complexity of multi side stuff and infinite scroll for discoverability. Maybe worth considering

**Comment by NilsJacobsen** [comment] 2024-04-10 13:53
Maybe:) Let's discuss that at a later point.

**Closed** 2024-04-24 08:22 UTC
Labels: Improvement
